apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: my-test-job
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: my-app:dev
        name: my-test-job
        resources: {}
      restartPolicy: Never
status: {}
