name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install OS dependencies for Playwright browsers
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-4-1 libgraphene-1.0-0 libwoff1 libvpx9 libevent-2.1-7 \
          libopus0 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 \
          libharfbuzz-icu0 libsecret-1-0 libhyphen0 libmanette-0.2-0 \
          libgles2 libx264-163

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install

    - name: Run Playwright tests
      run: npx playwright test
